apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.4.1
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "10m"
            memory: "20Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
          - mountPath: /data
            name: redis-pvc
      volumes:
        - name: redis-pvc
          persistentVolumeClaim:
            claimName: redis-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: NotIn
                    values:
                      - "true"
