services:
  db:
    restart: always

  backend:
    restart: always
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8000/api/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    restart: always
    ports:
      - "${FRONTEND_WEB_PORT_SERVER?Variable not set}:80"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    build:
      dockerfile: ./frontend/Dockerfile.prod
      context: .
      args:
        - NODE_ENV=production

  redis:
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
