"""renamed model_id to record_id in transactions

Revision ID: 0108b2671259
Revises: dacf5da1d2d2
Create Date: 2025-01-08 07:07:13.362092

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "0108b2671259"
down_revision = "dacf5da1d2d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("record_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("transactions", "model_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("model_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("transactions", "record_id")
    # ### end Alembic commands ###
