"""user expiry date is optional in invitations table

Revision ID: 01fb872a00a7
Revises: 1980b7b19dd3
Create Date: 2024-11-15 23:21:07.736079

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "01fb872a00a7"
down_revision = "1980b7b19dd3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invitation",
        "user_expiry_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invitation",
        "user_expiry_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    # ### end Alembic commands ###
