"""add metadata column to notifications table

Revision ID: 0dc635fc8cf0
Revises: 581c436281ae
Create Date: 2024-11-12 19:52:16.195273

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0dc635fc8cf0"
down_revision = "581c436281ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notification", sa.Column("meta_data", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification", "meta_data")
    # ### end Alembic commands ###
