"""updated expires_at and email_status_id fields in password_reset

Revision ID: 13fda1c1befa
Revises: 45d59060e780
Create Date: 2024-12-11 22:10:21.513941

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13fda1c1befa"
down_revision = "45d59060e780"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "password_reset", "email_status_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "password_reset", "email_status_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
