"""rename user suspended to deactivated

Revision ID: 93927e712a23
Revises: 32cdaa066e45
Create Date: 2025-04-14 01:19:18.562662+00:00

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "93927e712a23"
down_revision = "32cdaa066e45"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userstatus RENAME VALUE 'SUSPENDED' TO 'DEACTIVATED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userstatus RENAME VALUE 'DEACTIVATED' TO 'SUSPENDED'")
    # ### end Alembic commands ###
