"""update users table

Revision ID: 3b272478f2c1
Revises: 1a31ce608336
Create Date: 2024-11-09 19:59:10.380140

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "3b272478f2c1"
down_revision = "1a31ce608336"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    userstatus = sa.Enum(
        "ACTIVE",
        "PENDING_ADMIN_APPROVAL",
        "PENDING_EMAIL_VERIFICATION",
        "SUSPENDED",
        name="userstatus",
    )
    userstatus.create(op.get_bind())

    op.add_column(
        "user",
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
    )
    op.add_column("user", sa.Column("status", userstatus, nullable=False))
    op.add_column("user", sa.Column("last_login", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.drop_column("user", "full_name")
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user",
        sa.Column(
            "full_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("user", "last_login")
    op.drop_column("user", "status")
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
