"""create notifications table

Revision ID: 581c436281ae
Revises: 254a120b92d8
Create Date: 2024-11-12 18:48:26.684573

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "581c436281ae"
down_revision = "254a120b92d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("INFO", "WARNING", "ERROR", name="notificationtype"),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum("EMAIL", "WEB", "SMS", name="notificationchannel"),
            nullable=False,
        ),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("user", sa.Column("invitation_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "user", "invitation", ["invitation_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "invitation_id")
    op.drop_table("notification")
    # ### end Alembic commands ###
