"""add email_verification_token to user model

Revision ID: 969ff876d55f
Revises: 0108b2671259
Create Date: 2025-03-13 18:26:08.541152

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "969ff876d55f"
down_revision = "0108b2671259"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("email_verification_token", sa.Uuid(), nullable=True)
    )
    op.create_unique_constraint(
        "uq_user_email_verification_token", "user", ["email_verification_token"]
    )

    op.execute("ALTER TYPE emailtype ADD VALUE IF NOT EXISTS 'EMAIL_VERIFICATION'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_email_verification_token", "user", type_="unique")
    op.drop_column("user", "email_verification_token")
    # ### end Alembic commands ###
