"""remove email_status model

Revision ID: c8f87162f831
Revises: 969ff876d55f
Create Date: 2025-03-28 22:42:51.184081

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c8f87162f831"
down_revision = "969ff876d55f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # drop cascade email_status table
    op.execute("DROP TABLE IF EXISTS email_status CASCADE")
    op.drop_column("invitation", "email_status_id")
    op.drop_column("notification", "email_status_id")
    op.drop_column("password_reset", "email_status_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "password_reset",
        sa.Column("email_status_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "password_reset_email_status_id_fkey",
        "password_reset",
        "email_status",
        ["email_status_id"],
        ["id"],
    )
    op.add_column(
        "notification",
        sa.Column("email_status_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "notification_email_status_id_fkey",
        "notification",
        "email_status",
        ["email_status_id"],
        ["id"],
    )
    op.add_column(
        "invitation",
        sa.Column("email_status_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "invitation_email_status_id_fkey",
        "invitation",
        "email_status",
        ["email_status_id"],
        ["id"],
    )
    op.create_table(
        "email_status",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "SENT", "FAILED", name="emailstatusenum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "type",
            postgresql.ENUM(
                "INVITATION",
                "PASSWORD_RESET",
                "EMAIL_CONFIRMATION",
                "ALERT",
                "NOTIFICATION",
                "EMAIL_VERIFICATION",
                name="emailtype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_sent_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="email_status_pkey"),
    )
    # ### end Alembic commands ###
