"""create email status table

Revision ID: d11ca5a212d5
Revises: 3b272478f2c1
Create Date: 2024-11-11 20:29:44.937062

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "d11ca5a212d5"
down_revision = "3b272478f2c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", "FAILED", name="emailstatusenum"),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "INVITATION",
                "PASSWORD_RESET",
                "EMAIL_CONFIRMATION",
                "ALERT",
                "NOTIFICATION",
                name="emailtype",
            ),
            nullable=False,
        ),
        sa.Column("last_sent_date", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email_status")
    # ### end Alembic commands ###
