"""create transactions table

Revision ID: dacf5da1d2d2
Revises: 0c85b04e328d
Create Date: 2025-01-02 20:31:58.943147

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "dacf5da1d2d2"
down_revision = "0c85b04e328d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "model",
            sa.Enum("GROUP", "INVITATION", "USER", name="model"),
            nullable=False,
        ),
        sa.Column("model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "action",
            sa.Enum("CREATE", "UPDATE", "DELETE", name="action"),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    # ### end Alembic commands ###
