"""update invitations table

Revision ID: eefbd3f2312f
Revises: 13fda1c1befa
Create Date: 2024-12-13 06:23:15.421190

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eefbd3f2312f"
down_revision = "13fda1c1befa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invitation", sa.Column("expires_at", sa.DateTime(), nullable=False))
    op.drop_column("invitation", "active")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invitation",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("invitation", "expires_at")
    # ### end Alembic commands ###
