"""delete cascade invitation on user delete

Revision ID: f10793afdf57
Revises: 7fa58b9f74ba
Create Date: 2024-12-05 23:09:13.928527

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "f10793afdf57"
down_revision = "7fa58b9f74ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "invitation_created_by_user_id_fkey", "invitation", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "invitation", "user", ["created_by_user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invitation", type_="foreignkey")
    op.create_foreign_key(
        "invitation_created_by_user_id_fkey",
        "invitation",
        "user",
        ["created_by_user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
