apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: default-config-map
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: default-config-map
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: default-config-map
                key: POSTGRES_DB
        resources:
          requests:
            cpu: "20m"
            memory: "64Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-pvc
      volumes:
        - name: db-pvc
          persistentVolumeClaim:
            claimName: db-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: NotIn
                    values:
                      - "true"
